package com.elysium.mobs.client.model;

import com.elysium.mobs.entity.ElysiumMob;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

/**
 * GENERATED by tools/gen_mobs.py. Do not edit.
 *
 * The box table lives in that script, and the texture sheet is generated from
 * the same table - so the UVs here and the pixels there cannot disagree. Edit
 * the table and re-run.
 */
public class ChoirModel<T extends ElysiumMob> extends EntityModel<T> {

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart armLeft;
    private final ModelPart armRight;
    private final ModelPart legLeft;
    private final ModelPart legRight;

    public ChoirModel(ModelPart root) {
        this.root = root;
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.armLeft = root.getChild("arm_left");
        this.armRight = root.getChild("arm_right");
        this.legLeft = root.getChild("leg_left");
        this.legRight = root.getChild("leg_right");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head",
                CubeListBuilder.create().texOffs(0, 0)
                        .addBox(-4.0F, -7.0F, -4.0F, 8, 7, 8),
                PartPose.offset(0.0F, 11.0F, 0.0F));
        PartDefinition body = root.addOrReplaceChild("body",
                CubeListBuilder.create().texOffs(0, 15)
                        .addBox(-5.0F, 0.0F, -3.0F, 10, 10, 6),
                PartPose.offset(0.0F, 11.0F, 0.0F));
        root.addOrReplaceChild("arm_left",
                CubeListBuilder.create().texOffs(32, 15)
                        .addBox(-1.0F, -1.0F, -2.0F, 4, 12, 4),
                PartPose.offset(6.0F, 12.0F, 0.0F));
        root.addOrReplaceChild("arm_right",
                CubeListBuilder.create().texOffs(32, 15)
                        .addBox(-3.0F, -1.0F, -2.0F, 4, 12, 4),
                PartPose.offset(-6.0F, 12.0F, 0.0F));
        root.addOrReplaceChild("leg_left",
                CubeListBuilder.create().texOffs(32, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4, 6, 4),
                PartPose.offset(2.0F, 18.0F, 0.0F));
        root.addOrReplaceChild("leg_right",
                CubeListBuilder.create().texOffs(32, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4, 6, 4),
                PartPose.offset(-2.0F, 18.0F, 0.0F));
        body.addOrReplaceChild("arm_second_left",
                CubeListBuilder.create().texOffs(48, 0)
                        .addBox(0.0F, 0.0F, -1.0F, 3, 9, 3),
                PartPose.offset(5.0F, 3.0F, 0.0F));
        body.addOrReplaceChild("arm_second_right",
                CubeListBuilder.create().texOffs(48, 0)
                        .addBox(-3.0F, 0.0F, -1.0F, 3, 9, 3),
                PartPose.offset(-5.0F, 3.0F, 0.0F));
        body.addOrReplaceChild("arm_third_left",
                CubeListBuilder.create().texOffs(48, 15)
                        .addBox(0.0F, 0.0F, -1.0F, 2, 7, 2),
                PartPose.offset(5.0F, 6.0F, 0.0F));
        body.addOrReplaceChild("arm_third_right",
                CubeListBuilder.create().texOffs(48, 15)
                        .addBox(-2.0F, 0.0F, -1.0F, 2, 7, 2),
                PartPose.offset(-5.0F, 6.0F, 0.0F));
        head.addOrReplaceChild("hood",
                CubeListBuilder.create().texOffs(0, 31)
                        .addBox(-5.0F, -9.0F, -5.0F, 10, 3, 10),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    /**
     * Walk and look, and nothing else.
     *
     * Deliberately the same animation for every family. A distinctive walk is
     * worth having and is not worth guessing at without being able to watch it
     * - the silhouettes carry the difference, and an animation written blind is
     * more likely to look broken than characterful.
     */
    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount,
                          float ageInTicks, float netHeadYaw, float headPitch) {
        this.head.yRot = netHeadYaw * ((float) Math.PI / 180F);
        this.head.xRot = headPitch * ((float) Math.PI / 180F);

        float swing = (float) Math.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.legLeft.xRot = swing;
        this.legRight.xRot = -swing;
        this.armLeft.xRot = -swing * 0.8F;
        this.armRight.xRot = swing * 0.8F;
    }

    @Override
    public void renderToBuffer(PoseStack pose, VertexConsumer buffer, int light,
                               int overlay, int colour) {
        this.root.render(pose, buffer, light, overlay, colour);
    }
}
