package com.elysium.npcs.client;

import com.elysium.npcs.ElysiumNpcs;
import com.elysium.npcs.client.model.EnvoyModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;

/**
 * GENERATED by tools/gen_npcs.py. Do not edit.
 *
 * Client-only, and annotated so: a renderer class touched on a dedicated server
 * is a NoClassDefFoundError at load, and the annotation is what keeps this file
 * from ever being loaded there.
 */
@EventBusSubscriber(modid = ElysiumNpcs.MODID, bus = EventBusSubscriber.Bus.MOD,
        value = Dist.CLIENT)
public final class ElysiumNpcsClient {

    private ElysiumNpcsClient() {
    }

    public static final ModelLayerLocation ENVOY_LAYER = new ModelLayerLocation(
            ResourceLocation.fromNamespaceAndPath(ElysiumNpcs.MODID, "envoy"), "main");

    @SubscribeEvent
    public static void onLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
        event.registerLayerDefinition(ENVOY_LAYER, EnvoyModel::createBodyLayer);
    }

    @SubscribeEvent
    public static void onRenderers(EntityRenderersEvent.RegisterRenderers event) {
        event.registerEntityRenderer(ElysiumNpcs.ENVOY.get(), EnvoyRenderer::new);
    }
}
