package com.elysium.npcs.client;

import com.elysium.npcs.client.model.EnvoyModel;
import com.elysium.npcs.entity.ImperialEnvoy;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.resources.ResourceLocation;

/**
 * GENERATED by tools/gen_npcs.py. Do not edit.
 *
 * The texture comes from the envoy's kind, which is what lets one entity type
 * be five people.
 */
public class EnvoyRenderer extends MobRenderer<ImperialEnvoy, EnvoyModel<ImperialEnvoy>> {

    public EnvoyRenderer(EntityRendererProvider.Context context) {
        super(context, new EnvoyModel<>(context.bakeLayer(
                ElysiumNpcsClient.ENVOY_LAYER)), 0.5F);
    }

    @Override
    public ResourceLocation getTextureLocation(ImperialEnvoy entity) {
        return entity.getKind().texture();
    }
}
