package com.elysium.mobs.client;

import com.elysium.mobs.client.model.ReaverModel;
import com.elysium.mobs.entity.ElysiumMob;
import com.elysium.mobs.variant.MobVariant;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.resources.ResourceLocation;

/**
 * GENERATED by tools/gen_mobs.py. Do not edit.
 *
 * The texture comes from the entity's variant rather than from a constant,
 * which is the whole reason six entity types can be thirty creatures. A mob
 * with no variant - spawned by a command, or whose variant's mod was removed -
 * falls back to the family's first sub-variant rather than to a missing
 * texture, because a purple-and-black mob reads as a crash and a plain one
 * reads as a plain one.
 */
public class ReaverRenderer extends MobRenderer<ElysiumMob, ReaverModel<ElysiumMob>> {

    private static final ResourceLocation FALLBACK =
            ResourceLocation.fromNamespaceAndPath("elysiummobs",
                    "textures/entity/reaver/chainbound.png");

    public ReaverRenderer(EntityRendererProvider.Context context) {
        super(context, new ReaverModel<>(context.bakeLayer(
                com.elysium.mobs.client.ElysiumMobLayers.REAVER)), 0.57F);
    }

    @Override
    public ResourceLocation getTextureLocation(ElysiumMob entity) {
        MobVariant variant = entity.getVariant();
        return variant == null ? FALLBACK : variant.getTexture();
    }
}
