package com.elysium.npcs.client.model;

import com.elysium.npcs.entity.EnvoyKind;
import com.elysium.npcs.entity.ImperialEnvoy;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

/**
 * GENERATED by tools/gen_npcs.py. Do not edit.
 *
 * One humanoid carrying every piece of regalia any of the five wears. Which
 * pieces are drawn is decided per entity in setupAnim, from the envoy's own
 * kind - so a Sentinel has a visor and no crown without there being a second
 * model, and adding a sixth member of the court is a row in a table.
 */
public class EnvoyModel<T extends ImperialEnvoy> extends EntityModel<T> {

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart armLeft;
    private final ModelPart armRight;
    private final ModelPart legLeft;
    private final ModelPart legRight;

    private final ModelPart crown;
    private final ModelPart halo;
    private final ModelPart visor;
    private final ModelPart collar;
    private final ModelPart cape;
    private final ModelPart pauldronLeft;
    private final ModelPart pauldronRight;

    public EnvoyModel(ModelPart root) {
        this.root = root;
        this.head = root.getChild("head");
        this.armLeft = root.getChild("arm_left");
        this.armRight = root.getChild("arm_right");
        this.legLeft = root.getChild("leg_left");
        this.legRight = root.getChild("leg_right");

        this.crown = this.head.getChild("crown");
        this.halo = this.head.getChild("halo");
        this.visor = this.head.getChild("visor");
        ModelPart body = root.getChild("body");
        this.collar = body.getChild("collar");
        this.cape = body.getChild("cape");
        this.pauldronLeft = this.armLeft.getChild("pauldron_left");
        this.pauldronRight = this.armRight.getChild("pauldron_right");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head",
                CubeListBuilder.create().texOffs(0, 0)
                        .addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition body = root.addOrReplaceChild("body",
                CubeListBuilder.create().texOffs(32, 0)
                        .addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition armLeft = root.addOrReplaceChild("arm_left",
                CubeListBuilder.create().texOffs(56, 0)
                        .addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4),
                PartPose.offset(5.0F, 2.0F, 0.0F));
        PartDefinition armRight = root.addOrReplaceChild("arm_right",
                CubeListBuilder.create().texOffs(56, 0)
                        .addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4),
                PartPose.offset(-5.0F, 2.0F, 0.0F));
        root.addOrReplaceChild("leg_left",
                CubeListBuilder.create().texOffs(56, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4),
                PartPose.offset(2.0F, 12.0F, 0.0F));
        root.addOrReplaceChild("leg_right",
                CubeListBuilder.create().texOffs(56, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4),
                PartPose.offset(-2.0F, 12.0F, 0.0F));
        head.addOrReplaceChild("crown",
                CubeListBuilder.create().texOffs(0, 16)
                        .addBox(-4.0F, -11.0F, -4.0F, 8, 3, 8),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("halo",
                CubeListBuilder.create().texOffs(0, 27)
                        .addBox(-5.0F, -12.0F, -5.0F, 10, 4, 10),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        head.addOrReplaceChild("visor",
                CubeListBuilder.create().texOffs(72, 0)
                        .addBox(-4.0F, -6.0F, -5.0F, 8, 3, 1),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("collar",
                CubeListBuilder.create().texOffs(32, 16)
                        .addBox(-5.0F, 0.0F, -3.0F, 10, 3, 6),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        body.addOrReplaceChild("cape",
                CubeListBuilder.create().texOffs(0, 41)
                        .addBox(-5.0F, 0.0F, 2.0F, 10, 16, 1),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        armLeft.addOrReplaceChild("pauldron_left",
                CubeListBuilder.create().texOffs(64, 16)
                        .addBox(-1.0F, -3.0F, -3.0F, 6, 4, 6),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        armRight.addOrReplaceChild("pauldron_right",
                CubeListBuilder.create().texOffs(64, 16)
                        .addBox(-5.0F, -3.0F, -3.0F, 6, 4, 6),
                PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 96, 96);
    }

    /**
     * A walk, a look, and the regalia this particular person wears.
     *
     * Visibility is set every frame rather than once at construction because
     * one model instance draws every envoy on screen: a model built for the
     * Emperor and then used to draw a Sentinel would put a crown on the
     * Sentinel. Setting it per entity is the cost of having one model, and it
     * is seven booleans.
     */
    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount,
                          float ageInTicks, float netHeadYaw, float headPitch) {
        this.head.yRot = netHeadYaw * ((float) Math.PI / 180F);
        this.head.xRot = headPitch * ((float) Math.PI / 180F);

        float swing = (float) Math.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.legLeft.xRot = swing;
        this.legRight.xRot = -swing;
        this.armLeft.xRot = -swing * 0.7F;
        this.armRight.xRot = swing * 0.7F;

        EnvoyKind kind = entity.getKind();
        this.crown.visible = kind.wears(EnvoyKind.Regalia.CROWN);
        this.halo.visible = kind.wears(EnvoyKind.Regalia.HALO);
        this.visor.visible = kind.wears(EnvoyKind.Regalia.VISOR);
        this.collar.visible = kind.wears(EnvoyKind.Regalia.COLLAR);
        this.cape.visible = kind.wears(EnvoyKind.Regalia.CAPE);
        this.pauldronLeft.visible = kind.wears(EnvoyKind.Regalia.PAULDRONS);
        this.pauldronRight.visible = kind.wears(EnvoyKind.Regalia.PAULDRONS);
    }

    @Override
    public void renderToBuffer(PoseStack pose, VertexConsumer buffer, int light,
                               int overlay, int colour) {
        this.root.render(pose, buffer, light, overlay, colour);
    }
}
